/**
 *
 */
package hr.mladenc.model.constants;

/**
 * @author mladenc
 *
 */
public enum ValidationConstants {
    VALIDATION_OK, MESSAGE_ID_MANDATORY, TIMESTAMP_MANDATORY, PROTOCOL_VERSION_MANDATORY, MESSAGE_ID_NOT_POSITIVE, TIMESTAMP_NOT_POSITIVE, PROTOCOL_VERSION_INVALID_FORMAT, NOT_MESSAGE_OBJECT

}
